<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://services.perukai.das.ubp.edu.ar/" xmlns:tns="http://services.perukai.das.ubp.edu.ar/" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="ActualizarContenidosNoPublicadosRequest" type="tns:ActualizarContenidosNoPublicadosRequest"/>

  <xs:element name="ActualizarContenidosNoPublicadosResponse" type="tns:ActualizarContenidosNoPublicadosResponse"/>

  <xs:element name="ActualizarReservaClienteRequest" type="tns:ActualizarReservaClienteRequest"/>

  <xs:element name="ActualizarReservaClienteResponse" type="tns:ActualizarReservaClienteResponse"/>

  <xs:element name="CrearReservaDesdeRistorinoRequest" type="tns:CrearReservaDesdeRistorinoRequest"/>

  <xs:element name="CrearReservaDesdeRistorinoResponse" type="tns:CrearReservaDesdeRistorinoResponse"/>

  <xs:element name="ObtenerContenidosNoPublicadosRequest" type="tns:ObtenerContenidosNoPublicadosRequest"/>

  <xs:element name="ObtenerContenidosNoPublicadosResponse" type="tns:ObtenerContenidosNoPublicadosResponse"/>

  <xs:element name="ObtenerProvinciasRequest" type="tns:ObtenerProvinciasRequest"/>

  <xs:element name="ObtenerProvinciasResponse" type="tns:ObtenerProvinciasResponse"/>

  <xs:element name="RegistrarClickContenidoRequest" type="tns:RegistrarClickContenidoRequest"/>

  <xs:element name="RegistrarClickContenidoResponse" type="tns:RegistrarClickContenidoResponse"/>

  <xs:complexType name="ActualizarReservaClienteRequest">
    <xs:sequence>
      <xs:element name="ActualizarReservaClienteRequest" type="tns:actualizarReservaClienteRequestBean" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="actualizarReservaClienteRequestBean">
    <xs:sequence>
      <xs:element name="cantAdultos" type="xs:int" minOccurs="0"/>
      <xs:element name="cantMenores" type="xs:int" minOccurs="0"/>
      <xs:element name="codEstado" type="xs:int" minOccurs="0"/>
      <xs:element name="codReservaSucursal" type="xs:string" minOccurs="0"/>
      <xs:element name="fechaCancelacion" type="xs:string" minOccurs="0"/>
      <xs:element name="fechaReserva" type="xs:string" minOccurs="0"/>
      <xs:element name="horaReserva" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ActualizarReservaClienteResponse">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="RegistrarClickContenidoRequest">
    <xs:sequence>
      <xs:element name="Body" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RegistrarClickContenidoResponse">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="ObtenerProvinciasRequest">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="ObtenerProvinciasResponse">
    <xs:sequence>
      <xs:element name="ProvinciasResponse" type="tns:provinciaBean" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="provinciaBean">
    <xs:sequence>
      <xs:element name="codProvincia" type="xs:string" minOccurs="0"/>
      <xs:element name="nomProvincia" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ActualizarContenidosNoPublicadosRequest">
    <xs:sequence>
      <xs:element name="Body" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ActualizarContenidosNoPublicadosResponse">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="CrearReservaDesdeRistorinoRequest">
    <xs:sequence>
      <xs:element name="Body" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CrearReservaDesdeRistorinoResponse">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="ObtenerContenidosNoPublicadosRequest">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="ObtenerContenidosNoPublicadosResponse">
    <xs:sequence>
      <xs:element name="SoapStringResponse" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

